
Running on CPU

2021-05-26 19:27:44.110360: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-26 19:27:44.130772: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2900000000 Hz
2021-05-26 19:27:44.132444: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555813a160 executing computations on platform Host. Devices:
2021-05-26 19:27:44.132460: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2021-05-26 19:27:44.788113: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.

TensorFlow version = 2.0.0

Not connected to GPU

train_images.shape = (60000, 784)
train_labels.shape = (60000,)
test_images.shape = (10000, 784)
test_labels.shape = (10000,)

Training starting...
Traceback (most recent call last):
  File "./hpc.py", line 78, in <module>
    model.fit(train_images, train_labels, epochs=10)
  File "/home/aj928/.conda/envs/tf-mnist2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/aj928/.conda/envs/tf-mnist2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "/home/aj928/.conda/envs/tf-mnist2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/aj928/.conda/envs/tf-mnist2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 594, in _process_inputs
    steps=steps)
  File "/home/aj928/.conda/envs/tf-mnist2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2472, in _standardize_user_data
    exception_prefix='input')
  File "/home/aj928/.conda/envs/tf-mnist2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 565, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected flatten_input to have 3 dimensions, but got array with shape (60000, 784)
